### ISSUE TITLE
大佬，咨询几个问题

### ISSUE THREAD

**Issue by young-fire** [bubbliiiing/ssd-pytorch#36]
SSD和SSdlite 是同一个模型吗，只是主干网络不同？ 还有SSD300 和 ssdlite320 后面的数字是啥意思

**Comment by bubbliiiing** [comment]
不是，还有深度可分离卷积
输入图片分辨率

**Comment by young-fire** [comment]
哦哦 明白了，多谢

**Comment by young-fire** [comment]
大佬，有没有群啊，想入群学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 下午4:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bubbliiiing/ssd-pytorch] 大佬，咨询几个问题 (#36)





 
不是，还有深度可分离卷积
 输入图片分辨率

**Comment by bubbliiiing** [comment]
没有呀，没创建
