### ISSUE TITLE
预测出错

### ISSUE THREAD

**Issue by lifeaddicted** [bubbliiiing/ssd-pytorch#47]
up，我在预测的是出了这个问题，具体原因是什么呢
![image](https://user-images.githubusercontent.com/50570612/148678628-6d30c9cb-f27d-425e-bf13-8bcaea3ca4e8.png)

**Comment by lifeaddicted** [comment]
解决了解决了，没有设置打开方式😓

**Comment by bubbliiiing** [comment]
加油啊
