### ISSUE TITLE
训练出现bug

### ISSUE THREAD

**Issue by ChristmasLee** [bubbliiiing/ssd-pytorch#75]
![image](https://user-images.githubusercontent.com/57053404/181484983-8626d843-0d31-408d-9e63-b29a166983ff.png)
想问一下b导，从主干预训练权重开始训练，前50是冻结训练，batchsize=8；之后是解冻训练，batchsize=4，结果训练中每10个epoch验证一次的epoch突然先降再升，这是因为什么呢？

**Comment by bubbliiiing** [comment]
结合数据集来看吧

**Comment by ChristmasLee** [comment]
> 结合数据集来看吧

b导，我同样的数据集和训练方式，其他网络例如yolov3,yolov5等都没问题，只有ssd是在解冻训练的第一个epoch突然mAP降为0了，是学习率的问题吗？因为其他的网络sgd学习率是1e-2，ssd是2e-3，但是我调成了1e-2，谢谢

**Comment by bubbliiiing** [comment]
……默认来，谢谢。

**Comment by ChristmasLee** [comment]
> ……默认来，谢谢。

谢谢b导，SSD问题已解决。
