### ISSUE TITLE
关于对先验框进行制定的aspect_ratios参数设置

### ISSUE THREAD

**Issue by EticosCheng** [bubbliiiing/ssd-pytorch#88]
老师好，我在使用此模型将VGG换成Denseblock时，将每个特征层的每个特征点对应的先验框数量由原有的(4、6、6、6、4、4)替换成了(8、8、8、8、8、8)，最后共有13888个先验框。想请教的是在utils/anchors.py文件中的aspect_ratios应该怎么改？
或者请您说一说为什么在原有的参数设置中[1, 2]为4而[1, 2,3]为6？
期待解答，感谢！

**Comment by EticosCheng** [comment]
感谢，通过研读您的代码和资料，我逐渐理解了一切，并顺利解决了！

**Comment by bubbliiiing** [comment]
OKOK加油
